import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { getFirebaseAdmin } from "../firebase-admin";

// Mirrors the Flutter app's SupportMessageModel + DirectSupportChatRepo
// behavior — message shape and the support/{userId} doc fields must stay
// byte-for-byte compatible because both the Flutter admin and this web
// dashboard read the same Firestore data.

const AADI_FROM_ID = "0";
const SUPPORT_COLLECTION = "support";
const USERS_COLLECTION = "Users";

export type SupportMessage = {
  fromId: string;
  content: string;
  timestamp: Timestamp | null;
  type: "direct" | "autoGenerated";
};

export type DraftCategory =
  | "answerable"           // routine/navigation question — safe to draft a real answer
  | "investigation"        // bug report / account data issue — only hold/acknowledge
  | "account_change"       // refund / plan / subscription — only hold/acknowledge
  | "medical"              // dosing / side-effects / "is this normal" — only hold + redirect
  | "thanks";              // user says thanks/done — short close-out

export type DraftRecord = {
  content: string;
  generated_at: Timestamp;
  category: DraftCategory;
  model: string;
};

export type AwaitingConversation = {
  userId: string;
  lastMessage: SupportMessage;
  lastUpdateAt: Timestamp | null;
  draft: DraftRecord | null;
  skipUntil: Timestamp | null;
};

export type UserProfile = {
  userId: string;
  email: string | null;
  firstName: string | null;
  gender: string | null;
  treatmentStage: string | null;
  daysIntoProgram: number | null;
  region: "US" | "IN" | "OTHER" | null;
  plan: string | null;
};

export async function listAwaitingConversations(opts: { limit?: number } = {}): Promise<AwaitingConversation[]> {
  const { db } = getFirebaseAdmin();
  const snap = await db
    .collection(SUPPORT_COLLECTION)
    .orderBy("last_update_at", "desc")
    .limit(opts.limit ?? 200)
    .get();
  const now = Timestamp.now();
  const out: AwaitingConversation[] = [];
  for (const doc of snap.docs) {
    const data = doc.data() as Record<string, unknown>;
    const lastMessage = (data.last_message ?? null) as Record<string, unknown> | null;
    if (!lastMessage || typeof lastMessage.fromId !== "string") continue;
    // Waiting on us only when the last message is from the user, not from Aadi.
    if (lastMessage.fromId === AADI_FROM_ID) continue;
    const skipUntil = (data.skip_until ?? null) as Timestamp | null;
    if (skipUntil && skipUntil.toMillis() > now.toMillis()) continue;
    out.push({
      userId: doc.id,
      lastMessage: {
        fromId: lastMessage.fromId as string,
        content: (lastMessage.content as string) ?? "",
        timestamp: (lastMessage.timestamp ?? null) as Timestamp | null,
        type: ((lastMessage.type as string) ?? "direct") as SupportMessage["type"],
      },
      lastUpdateAt: (data.last_update_at ?? null) as Timestamp | null,
      draft: (data.last_draft ?? null) as DraftRecord | null,
      skipUntil,
    });
  }
  return out;
}

export async function getRecentMessages(userId: string, count = 20): Promise<SupportMessage[]> {
  const { db } = getFirebaseAdmin();
  const snap = await db
    .collection(SUPPORT_COLLECTION)
    .doc(userId)
    .collection("messages")
    .orderBy("timestamp", "desc")
    .limit(count)
    .get();
  const msgs = snap.docs.map((d) => {
    const x = d.data();
    return {
      fromId: x.fromId as string,
      content: (x.content as string) ?? "",
      timestamp: (x.timestamp ?? null) as Timestamp | null,
      type: ((x.type as string) ?? "direct") as SupportMessage["type"],
    };
  });
  // Restore chronological order (oldest first) for prompting.
  return msgs.reverse();
}

export async function getUserProfile(userId: string): Promise<UserProfile> {
  const { db } = getFirebaseAdmin();
  const doc = await db.collection(USERS_COLLECTION).doc(userId).get();
  if (!doc.exists) {
    return { userId, email: null, firstName: null, gender: null, treatmentStage: null, daysIntoProgram: null, region: null, plan: null };
  }
  const d = doc.data() as Record<string, unknown>;
  // Best-effort surface of fields we care about. KESHAH user docs aren't
  // strictly typed and field availability varies by user vintage.
  const startDate = d.start_date as { date?: string } | undefined;
  let daysIntoProgram: number | null = null;
  if (startDate?.date) {
    // start_date.date is stored in dd/MM/yyyy. Compute days since.
    const [dd, mm, yyyy] = startDate.date.split("/").map((s) => parseInt(s, 10));
    if (dd && mm && yyyy) {
      const start = Date.UTC(yyyy, mm - 1, dd);
      const delta = (Date.now() - start) / 86_400_000;
      daysIntoProgram = Math.max(0, Math.floor(delta));
    }
  }
  let region: UserProfile["region"] = null;
  const country = (d.country as string | undefined)?.toUpperCase?.();
  if (country === "US" || country === "USA") region = "US";
  else if (country === "IN" || country === "INDIA") region = "IN";
  else if (country) region = "OTHER";

  return {
    userId,
    email: (d.email as string) ?? null,
    firstName: ((d.first_name as string) ?? (d.name as string) ?? null) as string | null,
    gender: (d.selected_gender as string) ?? null,
    treatmentStage: (d.treatment_stage as string) ?? null,
    daysIntoProgram,
    region,
    plan: (d.subscription_plan as string) ?? null,
  };
}

// Returns N Aadi outbound replies sampled across all conversations.
// Used as voice examples in the system prompt. We deliberately keep
// only Aadi's outbound messages so other users' inbound content (which
// could contain personal info) never leaks across into a fresh draft.
export async function sampleAadiVoiceExamples(count = 12): Promise<string[]> {
  const { db } = getFirebaseAdmin();
  // Pull recent conversations and sample Aadi messages out of each. Keeps
  // the round-trip fast (one collection-group scan would be cleaner but
  // requires a composite index that may not exist).
  const supportSnap = await db
    .collection(SUPPORT_COLLECTION)
    .orderBy("last_update_at", "desc")
    .limit(40)
    .get();

  const examples: string[] = [];
  for (const doc of supportSnap.docs) {
    if (examples.length >= count * 3) break;
    const msgs = await db
      .collection(SUPPORT_COLLECTION)
      .doc(doc.id)
      .collection("messages")
      .orderBy("timestamp", "desc")
      .limit(6)
      .get();
    for (const m of msgs.docs) {
      const x = m.data();
      if (x.fromId !== AADI_FROM_ID) continue;
      const content = (x.content as string) ?? "";
      // Skip auto-generated and trivially short messages.
      if ((x.type as string) === "autoGenerated") continue;
      if (content.trim().length < 8 || content.length > 800) continue;
      examples.push(content.trim());
    }
  }
  // Shuffle and take N.
  for (let i = examples.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [examples[i], examples[j]] = [examples[j], examples[i]];
  }
  return examples.slice(0, count);
}

export async function saveDraft(userId: string, draft: { content: string; category: DraftCategory; model: string }): Promise<void> {
  const { db } = getFirebaseAdmin();
  await db.collection(SUPPORT_COLLECTION).doc(userId).update({
    last_draft: {
      content: draft.content,
      generated_at: Timestamp.now(),
      category: draft.category,
      model: draft.model,
    },
  });
}

export async function clearDraft(userId: string): Promise<void> {
  const { db } = getFirebaseAdmin();
  await db.collection(SUPPORT_COLLECTION).doc(userId).update({
    last_draft: FieldValue.delete(),
  });
}

// Send a reply as Aadi (fromId='0'). Mirrors DirectSupportChatRepo.sendMessage
// in keshah_admin/lib/data/repos/direct_support_chat_repo.dart so that messages
// produced here are indistinguishable from messages produced by the Flutter app.
export async function sendReply(userId: string, content: string): Promise<void> {
  const { db } = getFirebaseAdmin();
  const supportDoc = db.collection(SUPPORT_COLLECTION).doc(userId);
  const messageJson = {
    fromId: AADI_FROM_ID,
    content,
    type: "direct" as const,
    timestamp: FieldValue.serverTimestamp(),
  };
  await supportDoc.update({
    last_update_at: FieldValue.serverTimestamp(),
    last_message: messageJson,
    last_draft: FieldValue.delete(),
  });
  await supportDoc.collection("messages").add(messageJson);
}

// Defer a conversation for N hours — it won't appear in the queue until
// the deadline passes. Used when the human reviewer wants to skip the
// drafted reply and circle back later.
export async function deferConversation(userId: string, hours: number): Promise<void> {
  const { db } = getFirebaseAdmin();
  const skipUntil = Timestamp.fromMillis(Date.now() + hours * 3600_000);
  await db.collection(SUPPORT_COLLECTION).doc(userId).update({
    skip_until: skipUntil,
  });
}
