// Pull a large sample of Aadi's actual outbound support replies. Goal:
// (1) audit for "pinned video" / TikTok references that would leak via
//     voice-examples into the model's drafts
// (2) build a corpus to sanity-check the system-prompt VOICE_RULES
//     against how Aadi actually writes.
//
// Dumps the full sample to a file so we can read through it.

import { initializeApp, getApps, cert } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as fs from "fs";

if (!getApps().length) {
  const sa = JSON.parse(Buffer.from(process.env.FIREBASE_SERVICE_ACCOUNT || "", "base64").toString());
  initializeApp({ credential: cert(sa) });
}
const db = getFirestore();

const AADI_FROM_ID = "0";
const SUPPORT_COLLECTION = "support";

(async () => {
  // Pull up to 400 recent conversations, look at Aadi's outbound messages.
  const supportSnap = await db
    .collection(SUPPORT_COLLECTION)
    .orderBy("last_update_at", "desc")
    .limit(400)
    .get();

  console.log(`Scanning ${supportSnap.size} support conversations...`);

  const replies: { ts: string; userId: string; content: string }[] = [];

  for (const doc of supportSnap.docs) {
    const msgs = await db
      .collection(SUPPORT_COLLECTION)
      .doc(doc.id)
      .collection("messages")
      .orderBy("timestamp", "desc")
      .limit(20)
      .get();
    for (const m of msgs.docs) {
      const x = m.data();
      if (x.fromId !== AADI_FROM_ID) continue;
      if ((x.type as string) === "autoGenerated") continue;
      const content = (x.content as string) ?? "";
      if (content.trim().length < 4) continue;
      const ts = x.timestamp?.toDate?.()?.toISOString?.() ?? "(no ts)";
      replies.push({ ts, userId: doc.id, content: content.trim() });
    }
  }

  // Sort newest first
  replies.sort((a, b) => (a.ts < b.ts ? 1 : -1));

  console.log(`Found ${replies.length} Aadi outbound replies.\n`);

  // Quick stats on common "leak" phrases
  const phrases = [
    "pinned video",
    "tiktok",
    "instagram",
    "youtube",
    "bio link",
    "link in bio",
    "comment YES",
    "swipe",
    "—", // em dash
    "Best, Aadi",
    "Best,\nAadi",
    "Regards",
    "Cheers",
  ];

  console.log(`=== Phrase audit (case-insensitive) ===`);
  for (const p of phrases) {
    const re = new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
    const hits = replies.filter((r) => re.test(r.content));
    console.log(`  "${p}": ${hits.length} replies`);
  }

  // Length distribution
  const lengths = replies.map((r) => r.content.length).sort((a, b) => a - b);
  const pct = (p: number) => lengths[Math.floor((lengths.length - 1) * p)];
  console.log(`\n=== Length stats (chars) ===`);
  console.log(`  count: ${lengths.length}`);
  console.log(`  p25:   ${pct(0.25)}`);
  console.log(`  p50:   ${pct(0.5)}`);
  console.log(`  p75:   ${pct(0.75)}`);
  console.log(`  p90:   ${pct(0.9)}`);
  console.log(`  max:   ${lengths[lengths.length - 1]}`);

  // Sentence-count rough estimate
  const sentenceCounts = replies.map((r) => (r.content.match(/[.!?]+/g) || []).length || 1).sort((a, b) => a - b);
  console.log(`\n=== Sentence count (rough, by .!? markers) ===`);
  console.log(`  p50:   ${sentenceCounts[Math.floor(sentenceCounts.length * 0.5)]}`);
  console.log(`  p75:   ${sentenceCounts[Math.floor(sentenceCounts.length * 0.75)]}`);
  console.log(`  p90:   ${sentenceCounts[Math.floor(sentenceCounts.length * 0.9)]}`);

  // Dump full corpus to file for reading
  const outPath = "/tmp/aadi_replies_audit.txt";
  const out = replies
    .map((r, i) => `--- #${i + 1} | ${r.ts} | user=${r.userId} ---\n${r.content}\n`)
    .join("\n");
  fs.writeFileSync(outPath, out);
  console.log(`\nFull dump written to ${outPath}`);

  // Print latest 25 inline so we can eyeball immediately
  console.log(`\n=== Latest 25 replies (newest first) ===\n`);
  replies.slice(0, 25).forEach((r, i) => {
    console.log(`--- #${i + 1} | ${r.ts.slice(0, 16)} ---`);
    console.log(r.content);
    console.log();
  });

  process.exit(0);
})().catch((e) => { console.error("ERR:", e.message); process.exit(1); });
